<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>FruityLink.Llm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FruityLink.Core\FruityLink.Core.csproj" />
  </ItemGroup>

</Project>
