<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../src/FruityLink.Plugins.Python/FruityLink.Plugins.Python.csproj" />
    <Compile Include="../FruityLink.Scripting.Tests/RecordingControl.cs" Link="RecordingControl.cs" />
  </ItemGroup>
</Project>
