<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>FruityLink.Knowledge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="AngleSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FruityLink.Core\FruityLink.Core.csproj" />
  </ItemGroup>

</Project>
