# Every literal legacy address consumed by SDK operations must have a named diagnostic entry.
# This checks source/catalog coverage, not whether a recipe resolves on a particular FL build.
file(READ "${BRIDGE_SOURCE}/sigscan.cpp" catalog)
string(REGEX MATCHALL "\\{[ \t]*0,[ \t]*0x[0-9A-Fa-f]+" aliases "${catalog}")
set(known)
foreach(alias IN LISTS aliases)
    string(REGEX REPLACE ".*0x" "" address "${alias}")
    string(TOLOWER "${address}" address)
    list(APPEND known "${address}")
endforeach()

file(GLOB managed "${BRIDGE_SOURCE}/../../src/FruityLink.FlStudio/Inject/*.cs")
list(APPEND managed "${BRIDGE_SOURCE}/dllmain.cpp")
foreach(source IN LISTS managed)
    file(READ "${source}" content)
    string(REGEX MATCHALL "[A-Za-z]+Async\\(\"[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]+\"|rb\\(0x[0-9A-Fa-f]+" uses "${content}")
    foreach(use IN LISTS uses)
        string(REGEX REPLACE ".*\\(\"|.*\\(0x|\"" "" address "${use}")
        string(TOLOWER "${address}" address)
        if(NOT address IN_LIST known)
            message(FATAL_ERROR "Native alias ${address} in ${source} is missing from the symbol catalog")
        endif()
    endforeach()
endforeach()
message(STATUS "All literal managed and native legacy aliases have catalog entries")
